backend:
  name: github
  repo: tranthanhbinh-ttbi/GI
  branch: main
  base_url: https://genderinsights.vercel.app

media_folder: "src/public/uploads"
public_folder: "/uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "series"
    label: "Trang Series"
    folder: "src/content/series"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Danh mục", name: "category", widget: "select", options: ["Bài Viết", "Video", "Podcast"] }
      - { label: "Chủ đề", name: "topic", widget: "string" }
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Mô tả ngắn", name: "description", widget: "text" }
      - { label: "Ảnh bìa", name: "thumbnail", widget: "image" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
      - { label: "Ngày đăng", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm", dateFormat: "DD/MM/YYYY" }

  - name: "explore"
    label: "Trang Khám Phá"
    folder: "src/content/explore"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Chủ đề", name: "topic", widget: "string" }
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Mô tả ngắn", name: "description", widget: "text" }
      - { label: "Ảnh bìa", name: "thumbnail", widget: "image" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
      - { label: "Tác giả", name: "author", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm", dateFormat: "DD/MM/YYYY" }

  - name: "news"
    label: "Trang Tin Tức"
    folder: "src/content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Danh mục", name: "category", widget: "select", options: ["Gender Insights", "Đối Tác", "Truyền Thông"] }
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Mô tả ngắn", name: "description", widget: "text" }
      - { label: "Ảnh bìa", name: "thumbnail", widget: "image" }
      - { label: "Nội dung chi tiết", name: "body", widget: "markdown" }
      - { label: "Ngày đăng", name: "date", widget: "datetime", dateFormat: "DD/MM/YYYY" }